/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Libraries\Downloads\gbtd22\pong_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define PongBackgroundWidth 20
#define PongBackgroundHeight 18
#define PongBackgroundBank 0

extern unsigned char PongBackground[];

/* End of PONG_BG.H */
